### ISSUE TITLE
Z command does not work adds random strings to the input 

### ISSUE THREAD

**Issue by Sarthak950** [nanotee/zoxide.vim#12] opened 2024-04-12 04:56 UTC
https://github.com/nanotee/zoxide.vim/assets/93645760/8350dc7c-edf5-4dda-b5bf-28664c6affc9

here is the video recording for the error what is happening as it is hard to explain

**Comment by nanotee** [comment] 2024-04-13 20:16
I can't reproduce this on my end. These weird characters are VT100 escape sequences that hide the cursor (`\e[?25L`) and turn off autowrap (`\e[?7l`) respectively, but I don't know why they would be in your zoxide database. I can't diagnose the problem without more info, I'm afraid.

Your setup looks a bit unusual, is your `cd` command printing images to the terminal?

**Comment by Sarthak950** [comment] 2024-04-15 05:02
no sir cd command does not print images on the terminal there is a package that works with neofetch that does that and i am available to provide any information that is required

**Comment by nanotee** [comment] 2024-04-15 16:37
Could you run these commands in Neovim and paste the output here?

```vim
echomsg &shell &shellcmdflag
```

```vim
echomsg system('zoxide query --exclude ' .. getcwd() .. ' aqua')
```

```vim
echomsg system(['zoxide', 'query', '--exclude', getcwd(), 'aqua'])
```

**Comment by Sarthak950** [comment] 2024-04-15 17:17
echo &shell &shellcmdflag

![240415_22-42-44](https://github.com/nanotee/zoxide.vim/assets/93645760/2baaaee9-17ec-4ac9-a9bc-51484b7bfade)

echomsg system('zoxide query --exclude ' .. getcwd() .. ' aqua')
![240415_22-45-41](https://github.com/nanotee/zoxide.vim/assets/93645760/3c1ba7fc-5bd3-404a-bd65-b45ff4b6ec9a)

echomsg system(['zoxide', 'query', '--exclude', getcwd(), 'aqua'])
![240415_22-47-12](https://github.com/nanotee/zoxide.vim/assets/93645760/c9555fe2-e80d-4427-a851-512ac27ac5fb)

**Comment by Sarthak950** [comment] 2024-04-16 15:19
@nanotee these are the output i am getting

**Comment by Sarthak950** [comment] 2024-04-20 05:22
@nanotee Hey i just figured out that if i type the full path on the Z command it works flawless its just when we it have to hit his db 
i have cleared the Db but still the problem persist 
Please help me resolve this Thanks.

**Comment by nanotee** [comment] 2024-04-22 13:18
It seems neofetch runs even when the shell is used non-interactively, which causes problems when parsing the output of the command. I should probably refactor this plugin to bypass shells entirely, but in the meantime, try running neofetch only when the shell is used interactively:

```fish
# In ~/.config/fish/config.fish
if status --is-interactive
  # command to run neofetch
end
```

**Comment by Sarthak950** [comment] 2024-04-22 17:24
@nanotee man this things works very great, neofetch was also making developemnt harder as it runs slower

**Comment by nanotee** [comment] 2024-04-22 18:33
Glad to know this was useful :)
I'll go ahead and close this issue then

**Closed as completed by nanotee** 2024-04-22 18:33 UTC
